name: ${project.name}
main: de.erethon.vignette.example.Example
version: ${project.version}
api-version: 1.13
author: Daniel Saukel
description: ${project.description}
commands:
  test:
    description: Opens the test menu.
